# Generated by Django 4.1.2 on 2022-11-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='template_curr_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
