# Generated by Django 4.1.2 on 2022-11-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_template_curr_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='template_curr_index',
            new_name='_template_curr_index',
        ),
    ]
