# Generated by Django 4.1 on 2022-08-21 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('Dostępny', 'Dostępny'), ('Uszkodzony', 'Uszkodzony'), ('Zarezerwowany', 'Zarezerwowany'), ('Niedostępny', 'Niedostępny')], default='Dostępny', max_length=20)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('date_reserved', models.DateField(null=True)),
                ('date_borrowed', models.DateField(null=True)),
                ('borrower', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.category')),
            ],
        ),
    ]
