# Generated by Django 4.1.3 on 2023-01-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='belongs_to_set',
        ),
    ]
