# Generated by Django 4.1.2 on 2022-11-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['set_status']},
        ),
    ]
