# Generated by Django 4.1 on 2022-08-24 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stuff', '0002_alter_item_date_borrowed_alter_item_date_reserved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_borrowed',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_reserved',
        ),
        migrations.CreateModel(
            name='RentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('taken', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stuff.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
