# Generated by Django 4.1.3 on 2023-01-19 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stuff', '0002_remove_item_belongs_to_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='settemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='settemplate',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
