# Generated by Django 4.1 on 2022-09-06 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_remove_item_date_borrowed_remove_item_date_reserved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='borrower',
        ),
    ]
