# Generated by Django 4.1.2 on 2022-11-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_set_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
    ]
