# Generated by Django 4.1 on 2022-09-15 16:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stuff', '0004_remove_item_borrower'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentEvent',
            new_name='ReservationEvent',
        ),
    ]
