# Generated by Django 4.1.2 on 2022-11-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_remove_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Dostępny', 'Dostępny'), ('Uszkodzony', 'Uszkodzony')], default='Dostępny', max_length=20),
        ),
    ]
