# Generated by Django 4.1 on 2022-09-28 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0005_rename_rentevent_reservationevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationevent',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 28), null=True),
        ),
        migrations.AlterField(
            model_name='reservationevent',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 9, 28), null=True),
        ),
    ]
