# Generated by Django 4.1.2 on 2022-11-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0005_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='belongs_to_set',
            field=models.BooleanField(default=False),
        ),
    ]
