# Generated by Django 4.1 on 2022-09-28 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0006_alter_reservationevent_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationevent',
            name='end_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='reservationevent',
            name='start_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
