# Generated by Django 4.1.2 on 2022-10-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0007_alter_reservationevent_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default_item.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('Dostępny', 'Dostępny'), ('Uszkodzony', 'Uszkodzony'), ('Niedostępny', 'Niedostępny')], default='Dostępny', max_length=20),
        ),
    ]
