# Generated by Django 4.1.1 on 2022-10-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0008_item_image_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default_item.png', upload_to='item_pics'),
        ),
    ]
